void howtoplay()
{
    title();
    char c[5]="TABLE";
    printf("\t\t   How To Play\n\n");
    printf("   You have to guess the hidden word in 6 tries\n");
    printf("   and the color of the letters changes to show\n");
    printf("\t\thow close you are.\n\n");
    printf("      To start the game, just enter any word,\n");
    printf("\t\t   For example,\n\n");
    printf("\t  ");
    white(c[0]);
    printf(" ");
    yellow(c[1]);
    printf(" ");
    white(c[2]);
    printf(" ");
    yellow(c[3]);
    printf(" ");
    green(c[4]);
    printf("\n\n       T,B aren't in the target word at all.");
    printf("\n     A,L are in the word but in the wrong spot.");
    printf("\n      E is in the word and in the correc spot.\n\n");
    printf("\t\t Let's try again.\n\n\t  ");
    strcpy(c,"FLASH");
    green(c[0]);
    printf(" ");
    green(c[1]);
    printf(" ");
    green(c[2]);
    printf(" ");
    white(c[3]);
    printf(" ");
    white(c[4]);
    printf("\n\n\t\t    So close!\n\n\t  ");
    strcpy(c,"FLAME");
    green(c[0]);
    printf(" ");
    green(c[1]);
    printf(" ");
    green(c[2]);
    printf(" ");
    green(c[3]);
    printf(" ");
    green(c[4]);
    printf("\n\n\t\t     ");
    printfgreen("Got it!");
    printf("\n\n      Press any key to return to main menu.");
    getch();
}